### PR TITLE
Replaced `class..{ companion object }` with object

### PR DESCRIPTION
**Pull request by ISkylakeS**
Fixes # .

- [x] I have tested my changes.
- [ ] I didn't test my changes. I will do that in the following 7 days and agree that this Pull request will be closed if I don't test it in the named time span.
- [x] I know the language good enough for providing high-quality code.

Changes proposed in this pull request:
---

- Replaced class EvalFunctions (which has only companion object) with object declaration

### CODE REVIEW

**Comment by ISkylakeS** [comment]
@duncte123, at that moment I'm online from mobile, but I tested it some hours ago with Java 9.0.4 and Kotlin 1.2.31. So it must be okay.

**Comment by duncte123** [comment]
I won't merge this pr until I see your tests because I had a lot of trouble with this layout last time (aka corrupted bytecode)

**Comment by ISkylakeS** [comment]
Okay. But one more thing. In which format I must send them?

**Comment by duncte123** [comment]
just a screenshot of you using the functions in eval

**Comment by ISkylakeS** [comment]
Okay, test from Groovy eval:

Almost the same thing: calling functions with the @JvmStatic annotation from the object.

**Comment by duncte123** [comment]
I ment the code that you are trying to get into the bot

**Comment by Sanduhr32** [comment]
Due to an earlier stage of the bot that caused byte stacktraces we wont merge this.

**Pull request closed without merging**
